### ISSUE TITLE
Is it works on centos?

### ISSUE THREAD

**Issue by catfish34** [lxc-webpanel/LXC-Web-Panel#92]
When I try to run it on centos 6.5 I can see login page.
But after I try to login I have 500 err:
Debug:
176.26.8.XX - - [03/Dec/2015 12:46:19] "GET /static/img/glyphicons-halflings.png HTTP/1.1" 200 -
176.26.8.XX - - [03/Dec/2015 12:46:24] "POST /login HTTP/1.1" 302 -
176.26.8.XX - - [03/Dec/2015 12:46:24] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1701, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1689, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1687, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1360, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1358, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python2.6/site-packages/flask/app.py", line 1344, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/LXC-Web-Panel/lwp.py", line 100, in home
    listx = lxc.listx()
  File "/root/LXC-Web-Panel/lxclite/__init__.py", line 172, in listx
    state = info(container)['state']
  File "/root/LXC-Web-Panel/lxclite/__init__.py", line 126, in info
    output = _run('lxc-info -qn {}|grep -i "State\|PID"'.format(container),
ValueError: zero length field name in format

**Comment by googley** [comment]
Which version of lxc ?

**Comment by catfish34** [comment]
1.0.7
